In [127]:
import pandas as pd

## Loading the data

In [128]:
A = pd.read_csv(r"C:\Users\admin\Downloads\enhanced_taxi_fare_data.csv")
A

,Distance_km,Vehicle_Type,Hour_of_Day,Day_of_Week,Is_Peak_Hour,Traffic_Density_Index,Weather_Condition,Passenger_Count,Estimated_Duration_min,Surge_Multiplier,...,City_Region,Demand_In_Area,Booking_Lead_Time_min,Fare_Amount,Driver_Favorite_Cuisine,Car_License_Plate_Last_Digit,Passenger_App_Version,Device_Battery_Level,Music_Genre_Playing,Driver_Years_of_Experience
0,19.04,Mini,7,1,0,3,Clear,2,45.28,1.0,...,Urban,55,3,383.79,Fast Food,4,v4.2,32,News,22
1,47.56,Mini,8,1,1,3,Clear,1,106.06,1.4,...,Urban,90,51,1248.77,Italian,9,v5.0,25,Rock,6
2,36.73,Auto,21,4,1,2,Clear,4,81.16,1.4,...,Suburban,28,42,645.61,Fast Food,4,v4.1,26,Silence,8
3,30.13,Auto,9,0,1,5,Clear,2,71.94,1.4,...,Suburban,59,26,541.99,Fast Food,6,v4.1,8,Jazz,21
4,8.22,Auto,10,1,1,4,Cloudy,4,25.07,1.4,...,Urban,63,22,207.68,Fast Food,5,v4.2,38,Silence,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,39.72,Mini,6,6,0,7,Clear,3,95.25,1.0,...,Urban,26,5,765.29,Italian,6,v4.1,8,Jazz,17
99996,39.07,Mini,0,6,0,1,Clear,3,83.88,1.0,...,Rural,93,32,497.28,Fast Food,1,v5.0,62,Silence,11
99997,33.89,Bike,11,4,1,3,Clear,1,76.52,1.4,...,Suburban,68,9,402.21,Mexican,7,v4.2,19,Pop,3
99998,25.22,Mini,4,1,0,5,Rainy,1,60.52,1.3,...,Suburban,12,23,535.75,Fast Food,0,v4.1,94,Rock,22
99999,19.80,Bike,2,3,0,4,Cloudy,2,54.00,1.0,...,Rural,77,48,139.89,Italian,4,v4.2,75,Pop,21

## Information about the data

In [129]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Distance_km                   100000 non-null  float64
 1   Vehicle_Type                  100000 non-null  object
 2   Hour_of_Day                   100000 non-null  int64
 3   Day_of_Week                   100000 non-null  int64
 4   Is_Peak_Hour                  100000 non-null  int64
 5   Traffic_Density_Index         100000 non-null  int64
 6   Weather_Condition             100000 non-null  object
 7   Passenger_Count               100000 non-null  int64
 8   Estimated_Duration_min        100000 non-null  float64
 9   Surge_Multiplier              100000 non-null  float64
 10  Driver_Rating                 100000 non-null  float64
 11  City_Region                   100000 non-null  object
 12  Demand_In_Area                100000 non-null  int64
 13  Booking_Lead_Time_min         100000 non-null  int64
 14  Fare_Amount                   100000 non-null  float64
 15  Driver_Favorite_Cuisine       100000 non-null  object
 16  Car_License_Plate_Last_Digit  100000 non-null  int64
 17  Passenger_App_Version         100000 non-null  object
 18  Device_Battery_Level          100000 non-null  int64
 19  Music_Genre_Playing           100000 non-null  object
 20  Driver_Years_of_Experience    100000 non-null  int64
dtypes: float64(5), int64(10), object(6)
memory usage: 16.0+ MB

In [130]:
A.columns

Index(['Distance_km', 'Vehicle_Type', 'Hour_of_Day', 'Day_of_Week',
       'Is_Peak_Hour', 'Traffic_Density_Index', 'Weather_Condition',
       'Passenger_Count', 'Estimated_Duration_min', 'Surge_Multiplier',
       'Driver_Rating', 'City_Region', 'Demand_In_Area',
       'Booking_Lead_Time_min', 'Fare_Amount', 'Driver_Favorite_Cuisine',
       'Car_License_Plate_Last_Digit', 'Passenger_App_Version',
       'Device_Battery_Level', 'Music_Genre_Playing',
       'Driver_Years_of_Experience'],
      dtype='object')

## Dropping Irrelevant Features (Domain Knowledge)

In [131]:
A = A.drop(columns = ['Driver_Favorite_Cuisine','Car_License_Plate_Last_Digit', 'Passenger_App_Version',
                      'Device_Battery_Level', 'Music_Genre_Playing','Driver_Years_of_Experience'])

In [132]:
A

,Distance_km,Vehicle_Type,Hour_of_Day,Day_of_Week,Is_Peak_Hour,Traffic_Density_Index,Weather_Condition,Passenger_Count,Estimated_Duration_min,Surge_Multiplier,Driver_Rating,City_Region,Demand_In_Area,Booking_Lead_Time_min,Fare_Amount
0,19.04,Mini,7,1,0,3,Clear,2,45.28,1.0,4.3,Urban,55,3,383.79
1,47.56,Mini,8,1,1,3,Clear,1,106.06,1.4,4.9,Urban,90,51,1248.77
2,36.73,Auto,21,4,1,2,Clear,4,81.16,1.4,4.7,Suburban,28,42,645.61
3,30.13,Auto,9,0,1,5,Clear,2,71.94,1.4,4.7,Suburban,59,26,541.99
4,8.22,Auto,10,1,1,4,Cloudy,4,25.07,1.4,4.0,Urban,63,22,207.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,39.72,Mini,6,6,0,7,Clear,3,95.25,1.0,3.5,Urban,26,5,765.29
99996,39.07,Mini,0,6,0,1,Clear,3,83.88,1.0,4.5,Rural,93,32,497.28
99997,33.89,Bike,11,4,1,3,Clear,1,76.52,1.4,4.1,Suburban,68,9,402.21
99998,25.22,Mini,4,1,0,5,Rainy,1,60.52,1.3,4.8,Suburban,12,23,535.75
99999,19.80,Bike,2,3,0,4,Cloudy,2,54.00,1.0,4.7,Rural,77,48,139.89

## Numerical Columns

In [133]:
numeric = A.select_dtypes(exclude = 'object')
numeric.columns

Index(['Distance_km', 'Hour_of_Day', 'Day_of_Week', 'Is_Peak_Hour',
       'Traffic_Density_Index', 'Passenger_Count', 'Estimated_Duration_min',
       'Surge_Multiplier', 'Driver_Rating', 'Demand_In_Area',
       'Booking_Lead_Time_min', 'Fare_Amount'],
      dtype='object')

In [134]:
corr_matrix = A.corr(numeric_only=True)
print(corr_matrix['Fare_Amount'].sort_values(ascending=False))

Fare_Amount               1.000000
Distance_km               0.721777
Estimated_Duration_min    0.714421
Surge_Multiplier          0.267505
Is_Peak_Hour              0.221170
Hour_of_Day               0.074154
Traffic_Density_Index     0.016693
Demand_In_Area            0.004885
Driver_Rating             0.002430
Booking_Lead_Time_min     0.001552
Passenger_Count           0.000628
Day_of_Week              -0.002287
Name: Fare_Amount, dtype: float64

## Categorical Columns

In [135]:
categorical = A.select_dtypes(include = 'object')
categorical.columns

Index(['Vehicle_Type', 'Weather_Condition', 'City_Region'], dtype='object')

In [136]:
from scipy.stats import f_oneway

f_stat, p_value = f_oneway(
    A[A['Vehicle_Type'] == 'Mini']['Fare_Amount'],
    A[A['Vehicle_Type'] == 'Sedan']['Fare_Amount'],
    A[A['Vehicle_Type'] == 'SUV']['Fare_Amount'],
    A[A['Vehicle_Type'] == 'Auto']['Fare_Amount'],
    A[A['Vehicle_Type'] == 'Bike']['Fare_Amount']
)

print("F-statistic :", f_stat)
print("P-value :", p_value)

if p_value < 0.05:
    print("Vehicle_Type has significant relationship with Total_Fare")
else:
    print("No significant relationship")

F-statistic : 9036.661877820994
P-value : 0.0
Vehicle_Type has significant relationship with Total_Fare

In [137]:
from scipy.stats import f_oneway

f_stat, p_value = f_oneway(
    A[A['Weather_Condition'] == 'Clear']['Fare_Amount'],
    A[A['Weather_Condition'] == 'Cloudy']['Fare_Amount'],
    A[A['Weather_Condition'] == 'Rainy']['Fare_Amount'],
    A[A['Weather_Condition'] == 'Stormy']['Fare_Amount']
)

print("F-statistic :", f_stat)
print("P-value :", p_value)

if p_value < 0.05:
    print("Vehicle_Type has significant relationship with Total_Fare")
else:
    print("No significant relationship")

F-statistic : 776.273697323705
P-value : 0.0
Vehicle_Type has significant relationship with Total_Fare

In [138]:
from scipy.stats import f_oneway

f_stat, p_value = f_oneway(
    A[A['City_Region'] == 'Urban']['Fare_Amount'],
    A[A['City_Region'] == 'Suburban']['Fare_Amount'],
    A[A['City_Region'] == 'Rural']['Fare_Amount']
)

print("F-statistic :", f_stat)
print("P-value :", p_value)

if p_value < 0.05:
    print("Vehicle_Type has significant relationship with Total_Fare")
else:
    print("No significant relationship")

F-statistic : 1633.2547587767472
P-value : 0.0
Vehicle_Type has significant relationship with Total_Fare

## Feature Selection

- The ANOVA test indicates that categorical features like Vehicle_Type, Weather_Condition, and City_Region significantly influence Fare_Amount..
So,
1. Vehicle_Type
2. Weather_condition
3. City_Region using for training the model.

- As per the Correlation-Coefficient these input numerical features has the good relationship with output numerical features         
1) Distance_km               
2) Estimated_Duration_min    
3) Surge_Multiplier          
4) Is_Peak_Hour              
5) Hour_of_Day               
6) Traffic_Density_Index

## Splitting the data (Holdout Approach)

In [139]:
X = A.drop(columns = ['Demand_In_Area','Driver_Rating','Booking_Lead_Time_min','Passenger_Count','Fare_Amount',])
y = A['Fare_Amount']

In [140]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 23)

## Pipeline

In [141]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,PowerTransformer,StandardScaler

In [143]:
numerical_cols = ['Distance_km', 'Hour_of_Day', 'Day_of_Week', 'Is_Peak_Hour',
       'Traffic_Density_Index', 'Estimated_Duration_min',
       'Surge_Multiplier',]
nominal_cols = [ 'Vehicle_Type','Weather_Condition',]
ordinal_cols = ['City_Region']
order = [['Urban', 'Suburban', 'Rural']]

In [144]:
numerical_pipeline = Pipeline([('Imputation',SimpleImputer(strategy = 'mean')),
                               ('Scaling',StandardScaler()),
                               ('Power_transformation',PowerTransformer())])
numerical_pipeline

Pipeline(steps=[('Imputation', SimpleImputer()), ('Scaling', StandardScaler()),
                ('Power_transformation', PowerTransformer())])

In [145]:
ordinal_pipeline = Pipeline([('Imputation',SimpleImputer(strategy = 'most_frequent')),
                             ('Encoding',OrdinalEncoder(categories = order))])
ordinal_pipeline

Pipeline(steps=[('Imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding',
                 OrdinalEncoder(categories=[['Urban', 'Suburban', 'Rural']]))])

In [146]:
nominal_pipeline = Pipeline([('Imputation',SimpleImputer(strategy = 'most_frequent')),
                             ('Encoding',OneHotEncoder(dtype = 'int',drop = 'first',handle_unknown = 'ignore'))])
nominal_pipeline

Pipeline(steps=[('Imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding',
                 OneHotEncoder(drop='first', dtype='int',
                               handle_unknown='ignore'))])

## Column Transformer

In [147]:
Data_preprocessing = ColumnTransformer([('Numerical transformation',numerical_pipeline,numerical_cols),
                                        ('Ordinal trsansformation',ordinal_pipeline,ordinal_cols),
                                        ('Nominal transformation',nominal_pipeline,nominal_cols)])
Data_preprocessing

ColumnTransformer(transformers=[('Numerical transformation',
                                 Pipeline(steps=[('Imputation',
                                                  SimpleImputer()),
                                                 ('Scaling', StandardScaler()),
                                                 ('Power_transformation',
                                                  PowerTransformer())]),
                                 ['Distance_km', 'Hour_of_Day', 'Day_of_Week',
                                  'Is_Peak_Hour', 'Traffic_Density_Index',
                                  'Estimated_Duration_min',
                                  'Surge_Multiplier']),
                                ('Ordinal trsansformation',
                                 Pipeline(steps=...ion',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoding',
                                                  OrdinalEncoder(categories=[['Urban',
                                                                              'Suburban',
                                                                              'Rural']]))]),
                                 ['City_Region']),
                                ('Nominal transformation',
                                 Pipeline(steps=[('Imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoding',
                                                  OneHotEncoder(drop='first',
                                                                dtype='int',
                                                                handle_unknown='ignore'))]),
                                 ['Vehicle_Type', 'Weather_Condition'])])

In [148]:
Data_preprocessing.fit_transform(X)

array([[-4.33659564e-01, -6.49479793e-01, -1.00776075e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.56546887e+00, -5.05141874e-01, -1.00776075e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 8.05973426e-01,  1.37058006e+00,  4.91723429e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 6.06865851e-01, -7.21703686e-02,  4.91723429e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.69108360e-04, -1.08252755e+00, -1.00776075e+00, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-3.80433498e-01, -1.37125039e+00, -9.58706838e-03, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00]],
      shape=(100000, 15))

## Algorithms

### XGBoost

In [149]:
xgb = Pipeline([('Data_preprocessing',Data_preprocessing),
                ('XGBoost',XGBRegressor(max_depth=6,
        learning_rate=0.05,
        n_estimators= 200,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42))])
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
r2_score(y_test,y_pred)

0.9995317928592423

### KNN

In [157]:
lr = Pipeline([('Data Preprocessing',Data_preprocessing),
               ('Algorithm',KNeighborsRegressor())])
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.9873515734786129

### DecisionTree

In [158]:
dt = Pipeline([('Data Preprocessing',Data_preprocessing),
               ('Algorithm',DecisionTreeRegressor())])
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
r2_score(y_test,y_pred)

0.9994916286218605

## RandomForest

In [159]:
rf = Pipeline([('Data Preprocessing',Data_preprocessing),
               ('Algorithm',RandomForestRegressor())])
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
r2_score(y_test,y_pred)

0.9997246653381249

1) KNN - 0.98

2) XGBoost - 0.9995

3) DT - 0.992

4) RF -

### Checking the model

In [150]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_squared_error,root_mean_squared_error

xgb = Pipeline([('Data_Preprocessing',Data_preprocessing),
                ('Algorithm',XGBRegressor())])

xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
xgb_r2_score = r2_score(y_test,y_pred)

xgb_train_score = xgb.score(X_train,y_train)
xgb_test_score = xgb.score(X_test,y_test)

print('training score :', xgb_train_score)
print('testing score :', xgb_test_score)
print('R2 score :',xgb_r2_score)

training score : 0.9994159378690602
testing score : 0.9993040953876097
R2 score : 0.9993040953876097

# Deployement (Gradio)

In [153]:
import pandas as pd

def prediction( Distance_km, Vehicle_Type, Hour_of_Day, Day_of_Week,
                Is_Peak_Hour, Traffic_Density_Index, Weather_Condition,
                 Estimated_Duration_min, Surge_Multiplier,
                 City_Region):

    data = pd.DataFrame([[ Distance_km, Vehicle_Type, Hour_of_Day, Day_of_Week,
                          Is_Peak_Hour, Traffic_Density_Index, Weather_Condition,
                          Estimated_Duration_min, Surge_Multiplier,
                          City_Region,]],columns=['Distance_km', 'Vehicle_Type', 'Hour_of_Day', 'Day_of_Week',
                                        'Is_Peak_Hour', 'Traffic_Density_Index', 'Weather_Condition',
                                         'Estimated_Duration_min', 'Surge_Multiplier',
                                         'City_Region'
                                        ])

    result = xgb.predict(data)
    return f"The total fare is {result} rupees."

In [155]:
import gradio as gr

interface = gr.Interface(
    fn=prediction,
    inputs=[
        gr.Number(label="Distance"),
        gr.Dropdown(['Mini', 'Auto', 'Sedan', 'Bike', 'SUV'],label="Vehicle_Type"),
        gr.Number(label="Time(24H)"),
        gr.Dropdown([0,1,2,3,4,5,6],label = "Week"),
        gr.Dropdown([0,1],label = "Peak Hour"),
        gr.Number(label="Traffic Density"),
        gr.Dropdown(['Clear', 'Cloudy', 'Rainy', 'Stormy'],label = "Weather Condition"),
        gr.Number(label="Estimated_Duration_min"),
        gr.Dropdown([1. , 1.4, 1.3, 1.7],label = "Surge_Multiplier"),
        gr.Dropdown(['Urban', 'Suburban', 'Rural'],label = "City_Region")
        
        
        
    ],
    outputs="text",
    title="Taxi cab Fare Prediction"
)

interface.launch()

* Running on local URL:  http://127.0.0.1:7864
* To create a public link, set `share=True` in `launch()`.

## Pickle

In [160]:
import pickle

In [163]:
with open(r'F:\Uber taxi Fare prediction\prediction.pkl','wb') as file:
    pickle.dump(xgb,file)